Travis change origin from http to ssh

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,8 +27,9 @@ jobs:
     script:
     - cargo fmt --all -- --check
     - cargo clippy
-    - git tag "tavis-$TRAVIS_BUILD_NUMBER"
-    - git push --tags origin
+    - export GIT_TAG=travis-build-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d %H-%M-%S")
+    - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
+    - git push origin $GIT_TAG
     before_deploy: skip
     deploy: []
   - stage: Build
@@ -55,8 +56,19 @@ before_install:
   -in travis_encrypted/id_rsa.enc -out travis_encrypted/id_rsa -d
 - openssl aes-256-cbc -K $encrypted_b2704e9bbe4d_key -iv $encrypted_b2704e9bbe4d_iv
   -in travis_encrypted/id_rsa.pub.enc -out travis_encrypted/id_rsa.pub -d
-- chmod 0600 travis_encrypted/id_rsa{,.pub}
-- mv travis_encrypted/id_rsa{,.pub} ${HOME}/.ssh/
+- chmod 0400 travis_encrypted/id_rsa{,.pub}
+#- mv travis_encrypted/id_rsa{,.pub} ${HOME}/.ssh/
+- echo "Host github.com" > ${HOME}/.ssh/config
+- echo "  IdentityFile  $(pwd)/travis_encrypted/id_rsa" >> ~/.ssh/config
+- git remote set-url origin git@github.com:jensim/bitbucket_server_cli.git
+- git config --global user.email "builds@travis-ci.com"
+- git config --global user.name "Travis CI"
+- echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
+- |
+  if ! git push -v ; then
+    echo "git push error"
+    exit 1
+  fi
 
 install: cargo build --release --verbose
 
